test-postgres:
    docker-compose up -d postgres
    sleep 3
    PG_TEST_DATABASE_URL="postgres://postgres:postgres@localhost:5432" cargo test --features postgres

test-mysql:
    docker-compose up -d mysql
    sleep 10
    MYSQL_TEST_DATABASE_URL="mysql://root:mysql@127.0.0.1:3306/test" cargo test --features mysql

test-sqlite:
    cargo test --features sqlite

test:
    docker-compose up -d
    sleep 10
    PG_TEST_DATABASE_URL="postgres://postgres:postgres@localhost:5432" cargo test --features postgres
    MYSQL_TEST_DATABASE_URL="mysql://root:mysql@127.0.0.1:3306/test" cargo test --features mysql
    cargo test --features sqlite
